public class TiposOperadores{
public static void main(String[] args) {
    //apresentar o significado dos simbolos especiais de acordo com a linguagem de programação java
    // operador de atribuição (=) definir o valor inicial ou sobrescrever o valor de uma variavel.
    String nome = "ANDREA";
    int idade = 22;
    double peso = 68.5; // utiliza-se so o ponto
    char sexo = 'F'; // permite um unico caractere
    boolean doadorOrgao = false; // usando o false ou true
    Date dataNascimento =  new Date(); // tipos de nossa linguagem, classe aluno, fornecedor, deve anteceder com "new" e a classe ex.Date.
// operadores aritimiteicos
double soma = 10.5 + 15.7;
int subtração = 113 -25;
in multiplicação = 20 * 7;
int divisao = 15/3;
int modulo = 18 % 3;
double resultado = (10*7) + (20/4);
//concatenaçao
String nomeCompleto = "LINGUAGEM" + "JAVA";
    
}

}
